### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Pherenice1125** [zhangbihan999/stream-game-app#53]
It seems that "Heart" button has disappeared.
![Snipaste_2024-09-24_09-41-52](https://github.com/user-attachments/assets/cdcef7ef-b48d-48bc-bcff-35b8488f6e2b)

**Comment by Pherenice1125** [comment]
Via "app url in repo"

**Comment by ShoulderZ9** [comment]
But I can still see it here, maybe it's not a code problem?
![image](https://github.com/user-attachments/assets/7318723f-3c8a-4fe5-bf15-622dc28ee610)
